# -*- coding: utf-8 -*-
"""get_abs_diff_vectors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QoJK2txVVmfuOHMQZc9OE_lZvUcbB9ls
"""


import pandas as pd 
import csv
import numpy as np
import datetime
import pickle

def convert_to_float(data):
    data=data
    for i in data:
        for index,j in enumerate(i):
            i[index]=float(j)
    return data

def get_list_fromcsv(file):
    with open(file, newline='') as f:
        reader = csv.reader(f)
        data = list(reader)
    return data

data=get_list_fromcsv('C:/Users/anujp/Desktop/sort/Entity_Resolution_Project/data/csv_files/absolute difference vector/all_ds_pagetitles_wordembeddings.csv')
data=convert_to_float(data)
df1=pd.read_csv("C:/Users/anujp/Desktop/sort/Entity_Resolution_Project/data/csv_files/absolute difference vector/all_web_final_ds.csv")
spec_id_list=list(df1['spec_id'])
embeddings_dict=dict(zip(spec_id_list,data))

#df_lab_gt_split=np.array_split(df_lab_gt,16)
#df_splitted=df_lab_gt_split[0]
count=1
for df_lab_gt in pd.read_csv('C:/Users/anujp/Desktop/sort/Entity_Resolution_Project/data/csv_files/absolute difference vector/pairs_to_predict.csv',chunksize=10000000/2):
  print("creating new dataframe..."+str(count))
  df_lab_gt.to_csv("C:/Users/anujp/Desktop/sort/Entity_Resolution_Project/data/csv_files/absolute difference vector/pair files/final_pairs"+str(count)+".csv")
  new_df=pd.DataFrame()
  new_df['vector1']=df_lab_gt['left_spec_id'].apply(lambda x: np.array(embeddings_dict[x]))
  new_df['vector2']=df_lab_gt['right_spec_id'].apply(lambda x: np.array(embeddings_dict[x]))
  new_df['abs_diff']=(np.subtract(new_df['vector1'],new_df['vector2'])).abs()
  abs_diff_list=list(new_df['abs_diff'])
  df_absdiff=pd.DataFrame(abs_diff_list)
  df_absdiff.to_csv("C:/Users/anujp/Desktop/sort/Entity_Resolution_Project/data/csv_files/absolute difference vector/vector files/final_pairs_ds_diff"+str(count)+".csv")
  count = count+1
  abs_diff_list.clear()
